FROM python:3.6

EXPOSE 80
RUN apt-get update -y && apt-get install -y \
    nginx \
    sendmail \
    supervisor

RUN echo "daemon off;" >> /etc/nginx/nginx.conf
COPY etc/nginx.conf /etc/nginx/sites-available/default
COPY etc/supervisor.conf /etc/supervisor/conf.d/app.conf

WORKDIR /app

COPY requirements.txt /app

RUN pip install -r requirements.txt && \
    pip install gunicorn

ENV PYTHONPATH /app

CMD ["/app/manage.py","runserver", "0.0.0.0:80"]

# If you want to test the production setup
# CMD ["/usr/bin/supervisord","-n"]