# syntax=docker/dockerfile:experimental
FROM python:3.6

EXPOSE 80
RUN apt-get update -y
RUN mkdir ~/.ssh && echo "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


WORKDIR /app

ARG DJVOCAB_COMMIT=a0cfeba93ea805d3861e97e9c38fd27447e5b58a
ARG IFXURLS_COMMIT=72f75b3fcc9446fc5095ad747b3ed53d05bc4799
ARG IFXUSER_COMMIT=701eec94d06e83fcb42416b9fb07255569c4c2c4
ARG IFXAUTH_COMMIT=d184b09de3159c1d437171262f30d7f20c9b174c
ARG IFXMAIL_CLIENT_COMMIT=b649c6ed9edfa7cae5a402485e689fcaf1e3dc86

COPY requirements.txt /app

RUN --mount=type=ssh pip install --upgrade pip && \
    pip install 'Django>2.1,<3' && \
    pip install git+ssh://git@github.com/harvardinformatics/djvocab.git@${DJVOCAB_COMMIT} && \
    pip install git+ssh://git@github.com/harvardinformatics/ifxurls.git@${IFXURLS_COMMIT} && \
    pip install git+ssh://git@github.com/harvardinformatics/ifxuser.git@${IFXUSER_COMMIT} && \
    pip install git+ssh://git@github.com/harvardinformatics/ifxauth.git@${IFXAUTH_COMMIT} && \
    pip install git+ssh://git@github.com/harvardinformatics/ifxmail.client.git@${IFXMAIL_CLIENT_COMMIT} && \
    pip install -r requirements.txt

# Set Django setting DEBUG to True
ENV PYTHONPATH /app
ENV DJANGO_SETTINGS_MODULE bauer.settings

CMD ./wait-for-it.sh bauer-db:3306 -t 60 && \
    find /app -name "*.pyc" -type f -print0 | xargs -0 rm -f && \
    ./manage.py collectstatic --noinput && \
    ./manage.py makemigrations && \
    ./manage.py migrate && \
    ./manage.py loaddata ifxuser && \
    ./manage.py runserver 0.0.0.0:80 --insecure

