# Generated by Django 2.0.2 on 2018-04-19 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('cmd', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('log', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bcl2fastq', 'bcl2fastq'), ('fastqc', 'fastqc')], default='bcl2fastq', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bcl2fastq_Sample_Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('q30', models.FloatField()),
                ('cluster', models.IntegerField()),
                ('analysis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_num', models.IntegerField()),
                ('length', models.IntegerField()),
                ('indexed', models.BooleanField()),
                ('lane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing.Lane')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('start_after', models.DateTimeField()),
                ('requestor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('flowcell', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=100)),
                ('expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100)),
                ('index1', models.CharField(max_length=50)),
                ('index2', models.CharField(max_length=50)),
                ('lane_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Lane')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Run')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('complete', 'complete'), ('failed', 'failed')], default='pending', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='type',
            field=models.CharField(choices=[('nextseq', 'nextseq'), ('hiseq', 'hiseq')], default='nextseq', max_length=100),
        ),
        migrations.AddField(
            model_name='run',
            name='instrument_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Instrument'),
        ),
        migrations.AddField(
            model_name='request',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Run'),
        ),
        migrations.AddField(
            model_name='request',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Status'),
        ),
        migrations.AddField(
            model_name='read',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing.Run'),
        ),
        migrations.AddField(
            model_name='lane',
            name='run_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequencing.Run'),
        ),
        migrations.AddField(
            model_name='bcl2fastq_sample_analysis',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Sample'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='analysis_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.AnalysisType'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sequencing.Request'),
        ),
    ]
