# Generated by Django 2.0.2 on 2018-04-25 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0005_auto_20180420_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bcl2fastq_Sample_Analysis',
            new_name='Bcl2fastqSampleAnalysis',
        ),
        migrations.RenameField(
            model_name='lane',
            old_name='lane_num',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='read',
            old_name='read_num',
            new_name='number',
        ),
        migrations.AlterModelTable(
            name='analysistype',
            table='analysis_type',
        ),
        migrations.AlterModelTable(
            name='bcl2fastqsampleanalysis',
            table='bcl2fastq_sample_analysis',
        ),
    ]
