# Generated by Django 2.0.2 on 2018-05-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0006_auto_20180425_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='start_after',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
