# Generated by Django 2.0.2 on 2018-05-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0008_remove_read_lane_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='analysis_type_id',
            new_name='analysis_type',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='request_id',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='bcl2fastqsampleanalysis',
            old_name='analysis_id',
            new_name='analysis',
        ),
        migrations.RenameField(
            model_name='bcl2fastqsampleanalysis',
            old_name='sample_id',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='lane',
            old_name='run_id',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='read',
            old_name='run_id',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='run_id',
            new_name='run',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='run',
            old_name='instrument_id',
            new_name='instrument',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='lane_id',
            new_name='lane',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='run_id',
            new_name='run',
        ),
    ]
