# Generated by Django 2.0.2 on 2018-05-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0009_auto_20180507_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='run_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sequencing.RunType'),
        ),
    ]
