# Generated by Django 2.0.2 on 2018-05-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0010_auto_20180514_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='run_type',
            new_name='type',
        ),
    ]
