# Generated by Django 2.0.2 on 2018-05-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0011_auto_20180514_1931'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='runtype',
            table='run_type',
        ),
    ]
