# Generated by Django 2.0.2 on 2018-05-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0012_auto_20180514_1934'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bcl2fastqsampleanalysis',
            table='sequencing_bcl2fastq_sample_analysis',
        ),
        migrations.AlterModelTable(
            name='runtype',
            table='sequencing_run_type',
        ),
    ]
