# Generated by Django 2.0.2 on 2019-08-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0016_auto_20180705_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='step',
            field=models.CharField(blank=True, choices=[('demultiplex', 'demultiplex'), ('quality', 'quality'), ('count', 'count'), ('publish', 'publish')], max_length=100, null=True),
        ),
    ]
