# Generated by Django 2.2.5 on 2019-09-26 14:09

from django.db import migrations, models

def fill_sample_type_str(apps, schema_editor):
    '''
    One time fix to turn sample type into a string so we can use
    djvocab for it
    '''
    Sample = apps.get_model('sequencing', 'Sample')
    for sam in Sample.objects.prefetch_related('sample_type').all():
        if sam.sample_type_id:
            new_name = sam.sample_type.name
            if new_name == 'Other':
                new_name = 'other'
            sam.sample_type_str = new_name
            sam.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0018_sample_sample_type_str'),
    ]

    operations = [
        migrations.RunPython(fill_sample_type_str),
    ]
