# Generated by Django 2.2.5 on 2019-09-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0019_update_sample_type_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='sample_type',
        ),
        migrations.DeleteModel(
            name='SampleType',
        ),
    ]
