# Generated by Django 2.2.5 on 2019-09-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0020_auto_20190926_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='sample_type_str',
            new_name='sample_type',
        ),
    ]
