# Generated by Django 2.2.16 on 2020-09-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequencing', '0021_auto_20190926_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='index1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
